services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  databaseapp:
    container_name: databaseapp
    build:
      context: .
      dockerfile: ./Dockerfile.database
    ports:
      - "8001:8001"
    depends_on:
      - db
volumes:
  postgres_data:
