FROM python:3.9.6-slim

ENV POETRY_VERSION=2.1.3

RUN pip install "poetry==$POETRY_VERSION"
WORKDIR /app

COPY ./poetry.lock ./pyproject.toml ./
COPY ./README.md ./.env ./
COPY ./src/digit_classifier/__init__.py ./src/digit_classifier/__init__.py 
COPY ./src/digit_classifier/frontend ./src/digit_classifier/frontend

RUN poetry install --with frontend

EXPOSE 8500

CMD ["poetry", "run", "streamlit", "run", "src/digit_classifier/frontend/app.py", "--server.port=8500", "--server.address=0.0.0.0"]