services:
  db:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  databaseapp:
    container_name: databaseapp
    build:
      context: .
      dockerfile: ./Dockerfile.database
    ports:
      - "8001:8001"
    depends_on:
      - db
  modelapp:
    container_name: modelapp
    build:
      context: .
      dockerfile: ./Dockerfile.model
    ports:
      - "8000:8000"
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    ports:
      - "8500:8500"
    depends_on:
      - databaseapp
      - modelapp
volumes:
  postgres_data:
