FROM python:3.9.6-slim

ENV POETRY_VERSION=2.1.3 

RUN pip install "poetry==$POETRY_VERSION"
WORKDIR /app

COPY ./poetry.lock ./pyproject.toml ./
COPY ./README.md ./.env ./
COPY ./src/digit_classifier/__init__.py ./src/digit_classifier/__init__.py 
COPY ./src/digit_classifier/database ./src/digit_classifier/database

RUN poetry install --with database

EXPOSE 8001

CMD ["poetry", "run", "uvicorn", "digit_classifier.database.api:appdb", "--host", "0.0.0.0", "--port", "8001"]